name: Update XML

on:
  schedule:
    - cron: '* * * * *' # –ö–∞–∂–¥—É—é –º–∏–Ω—É—Ç—É
  workflow_dispatch: # üëà –î–æ–±–∞–≤–ª—è–µ–º —ç—Ç–æ

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download XML
        run:
          curl -A "Mozilla/5.0" -o exprates.xml
          https://vipchanger.com/res/xml/exprates.xml

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add exprates.xml
          git commit -m "–û–±–Ω–æ–≤–ª–µ–Ω–∏–µ XML" || exit 0
          git push
